# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nameOverride: ""
  fullnameOverride: ""

  # -- Domain suffix to be used for default hostpaths in ingress
  # override in different environments, or for each app
  # --set global.ingressSuffix
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca

  persistence:
    # -- If true, the Postgres chart is deployed
    deployPostgres: true

  # -- The used ledger. Will be used for default values. Any of: bosch-test, idu.
  ledger: bcovrin-test

bpa:
  image:
    repository: image-registry.openshift-image-registry.svc:5000/f6b17d-tools/bcgov-b2b
    pullPolicy: Always
    # --  Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: ""

  config:
    # -- Override name shown in the frontend (may contain whitespaces and so on). Default: Helm release name, capitalized
    nameOverride: ""

    # -- Override title shown in the browser tab. Default: Helm release name, capitalized (or NameOverride if given)
    titleOverride: ""
    security:
      enabled: true
    bootstrap:
      username: admin
      password: changeme
    webhook:
      # -- Optional: secures aca-py to backend webhook communication with an api-key
      key: ""
    ledger:
      browserUrlOverride: ""
      genesisUrlOverride: ""
    # -- The scheme that is used to register the profile endpoint on the ledger
    scheme: https
    web:
      only: false
    creddef:
      revocationRegistrySize: 3000
    imprint:
      enabled: false
      urlOverride: ""
    privacyPolicy:
      enabled: false
      urlOverride: ""
    i18n:
      locale: bcgov
      fallbackLocale: en
    # --  log4j2 configuration file which must be in the classpath. Use log4j2.xml for non-json.
    logConfigurationFile: log4j2.xml

  imagePullSecrets: []

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # Uncomment this to define your own hosts and override global.ingressSuffix
    # hosts:
    #     host:
    #     paths: ['/']
    tls: []
    #  - secretName: my-bpa-tls
    #    hosts:
    #      - my-bpa.local

  openshift:
    route:
      enabled: true
      path: "/"
      targetPort: http
      timeout: 2m
      tls:
        enabled: true
        insecureEdgeTerminationPolicy: None
        termination: edge
      wildcardPolicy: None

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

keycloak:
  enabled: false

  clientId: bbcm
  clientSecret: <use --set keycloak.clientSecret>

  config:
    rolesName: roles
    nameKey: preferred_username
    redirectUri: "${bpa.scheme}://${bpa.host}/logout"
    scopes: openid
    issuer: https://dev.oidc.gov.bc.ca/auth/realms/digitaltrust
    endsessionUrl: https://dev.oidc.gov.bc.ca/auth/realms/digitaltrust/protocol/openid-connect/logout
    vcauthn_pres_req_conf_id: bpa-wallet-access-dev
    
schemas:
  enabled: true
  minesActPermit:
    enabled: true
  emissionsProfile:
    enabled: true
  tsm:
    enabled: false
  config: {}
#    bank-account:
#      id: "M6Mbe3qx7vB4wpZF4sBRjt:2:bank_account:1.0"
#      label: "Bank Account"
#      defaultAttributeName: "iban"
#      restrictions:
#        - issuerDid: "${bpa.did.prefix}M6Mbe3qx7vB4wpZF4sBRjt"
#          label: "Demo Bank"
#    commercial-register:
#      id: "5mwQSWnRePrZ3oF67C4KqD:2:commercialregister:1.0"
#      label: "Commercial Register"
#      defaultAttributeName: "companyName"
#      restrictions:
#        - issuerDid: "${bpa.did.prefix}5mwQSWnRePrZ3oF67C4KqD"
#          label: "Commercial Register"

ux:
  # -- The ux preset configuration.
  # -- Allowed values: bcgov, custom, default
  # -- When using preset=default, no ux configmaps will be created; app runs with default configuration
  # -- When using preset=custom, you need to populate the config object.
  preset: custom
  config:
    buttons:
      primary:
        text: false
        outlined: false
      secondary:
        text: true
        outlined: false
    theme:
      dark: false
      themes:
        light:
          primary: '#4A148C'
          secondary: '#424242'
          accent: '#82B1FF'
          error: '#FF5252'
          info: '#2196F3'
          success: '#4CAF50'
          warning: '#FFC107'
          bgLight: "#FAFAFA"
          bgLight2: "#ECECEC"
          font: "#313132"
          anchor: "#1A5A96"
          anchorHover: "#3B99FC"
          icons: "#4A148C"    
    favicon:      
      href: "https://raw.githubusercontent.com/bcgov/mines-digital-trust/main/assets/material-design/black-24dp/1x/outline_domain_black_24dp.png"
    navigation:
      avatar:
        agent:
          enabled: true
          default: false
          src: "https://raw.githubusercontent.com/bcgov/mines-digital-trust/main/assets/material-design/black-24dp/2x/outline_domain_black_24dp.png"
          showName: true
#      settings:
#        location: "top"
#      about:
#        enabled: true
#      logout:
#        enabled: false
#    header:
#      logout:
#        enabled: true

acapy:
  image:
    repository: bcgovimages/aries-cloudagent
    pullPolicy: IfNotPresent
    # --  Overrides the image tag whose default is the chart appVersion.
    tag: py36-1.16-1_0.7.2

  adminURLApiKey: 2f9729eef0be49608c1cffd49ee3cc4a


  # The agent seed, 32 characters. Will be generated if not defined here
  agentSeed: ""

  labelOverride: ""

  readOnlyMode: false

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000


  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1001

  service:
    type: ClusterIP
    adminPort: 8031
    httpPort: 8030

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    # Uncomment this to define your own hosts and override global.ingressSuffix
    # hosts:
    #     host:
    #     paths: ['/']
    tls: []
    #  - secretName: my-acapy-tls
    #    hosts:
    #      - my-acapy.local

  openshift:
    route:
      enabled: true
      path: "/"
      targetPort: http
      timeout: 2m
      tls:
        enabled: true
        insecureEdgeTerminationPolicy: None
        termination: edge
      wildcardPolicy: None

  tails:
    # -- Set to true to enable revocation (external tails server required)
    enabled: false

    # -- Override the otherwise ledger-specifically generated base URL of the external tails server
    baseUrlOverride: ""

    # -- Override the otherwise ledger-specifically generated upload URL of the external tails server
    uploadUrlOverride: ""

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  staticArgs:
    autoAcceptInvites: true
    autoAcceptRequests: false
    autoRespondMessages: false
    autoRespondCredentialProposal: false
    autoRespondCredentialOffer: false
    autoRespondCredentialRequest: false
    autoRespondPresentationProposal: true
    autoRespondPresentationRequest: false
    autoStoreCredential: true
    autoVerifyPresentation: true
    autoPingConnection: true
    autoProvision: true
    monitorPing: true
    publicInvites: true
    logLevel: info

postgresql:
  # --  PostgreSQL service configuration
  service:
    port: 5432

  # --  PostgreSQL User to create. Do not change - otherwise non-admin user is created!
  postgresqlUsername: postgres

  # --  PostgreSQL Password for the new user. If not set, a random 10 characters password will be used.
  postgresqlPassword: change-me

  # -- PostgreSQL Database to create.
  postgresqlDatabase: bpa

  # --  Persistent Volume Storage configuration. ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:

    # -- Enable PostgreSQL persistence using Persistent Volume Claims.
    enabled: true
    size: 1Gi
    storageClass: netapp-file-standard
  image:
    tag: 12
  # -- add securityContext (fsGroup, runAsUser). These need to be false for Openshift 4
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 384Mi
    requests:
      cpu: 50m
      memory: 256Mi
